name: flutter_infinite_list
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 0.12.0
  equatable: ^0.2.0
  flutter_bloc: ^0.13.0

  analyzer: '>=0.33.3 <0.37.0'
  analyzer_plugin: '>=0.0.1-alpha.5 <0.0.1-alpha.9'
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  source_gen: ^0.9.0
  quiver: '>=0.21.0 <3.0.0'


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_test: ^0.10.3
  build_runner: ^1.0.0
  built_value_generator: ^6.1.3
  logging: ^0.11.0
  pedantic: ^1.4.0
  test: ^1.0.0

flutter:
  uses-material-design: true
